# Generated by Django 5.2 on 2025-04-07 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(help_text='Password must be at least 8 characters long', max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
