# Generated by Django 5.2 on 2025-04-07 16:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, help_text='Password must be at least 8 characters long', max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
